# This is a basic workflow to help you get started with Actions

name: Commit4Fun

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
    
  schedule:
    - cron: 0 12 * * *
  # Run job every day at 12:00 UTC

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shel
    - name: Create file to commit
      run: |
        mkdir -p directory
        rm -f directory/*
        newfile=$(date +'%s') && touch directory/$newfile
    - name: Configure Git
      run: |
        git config --local user.email "action-commit-bot@example.com"
        git config --local user.name "Dummy Fake Activity Bot"
        git add .
        git commit -m "Create fake activity commit" -a

    # Runs a set of commands using the runners shell
    - name: Push
      run: |
        git push
